- name: Create firewalld rule
  hosts: localhost
  become: true
  tasks:
    - name: Install firewalld svc
      package: 
        name: firewalld
        state: present
    - name: Start & Enable svc
      service:
        name: firewalld
        state: started
    - name: Creating firewalld rule for icmp protocol
      firewalld:
        service: icmp
        source: "{{ lookup('env', 'WEB1_IP')}}"
        zone: internal
        state: enabled
        permanent: true
        immediate: true
