- name: Demo Tomcat Server
  hosts: localhost
  become: true
  vars:
    java_package_name: java-11-amazon-corretto.x86_64
    tomcat_package_name: apache-tomcat-9.0.117
  tasks:
    - name: 'Install java package'
      package:
        name: '{{ java_package_name }}'
        state: present
      tags: 'Install-java'

    - name: 'Create tomcat group'
      group:
        name: tomcat
      tags: "Install-tomcat"

    - name: 'Create tomcat user'
      user:
        name: tomcat
        state: present
        uid: 1011
        group: tomcat
        home: /usr/share/tomcat
        createhome: false
      tags: "Install-tomcat"

    - name: 'Download Tomcat'
      get_url:
        url: 'https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.117/bin/{{ tomcat_package_name }}.tar.gz'
        dest: '/opt/'
      tags: "Install-tomcat"

    - name: 'Extract {{ tomcat_package_name }}.tar.gz file to /opt/ directory'
      unarchive:
        src: '/opt/{{ tomcat_package_name }}.tar.gz'
        dest: '/opt/'
        remote_src: true
      tags: "Install-tomcat"

    - name: Create symlink for Tomcat
      file:
        src: /opt/{{ tomcat_package_name }}
        path: /usr/share/tomcat
        state: link
      tags: "Install-tomcat"

    - name: 'Change ownership of /usr/share/tomcat/{{ tomcat_package_name }} directory'
      file:
        path: '/usr/share/tomcat/'
        owner: tomcat
        group: tomcat
        state: directory
        mode: '0755'
      tags: "Install-tomcat"

    - name: 'Start tomcat server'
      shell: '/usr/share/tomcat/bin/startup.sh'
