- name: Create Users & become_user Demo
  hosts: localhost
  vars:
    user_details:
      - name: Lion
        uid: 1011
      - name: Tiger
        uid: 1012
  tasks:
    - name: 'create user {{ item.name }} with uid  {{ item.uid }}'
      user:
        name: '{{ item.name }}'
        state: present
        uid: '{{ item.uid }}'
      with_items: '{{ user_details }}'
    - name: list out the users
      command: getent passwd
      register: getUsers_result
      changed_when: getUsers_result.rc == 0
      failed_when: getUsers_result.rc !=0  
    - name: Know the logged in user
      shell: whoami 
      register: whoami_result
      changed_when: whoami_result.rc == 0
      failed_when: whoami_result.rc !=0
