- name: To check the health status of servers
  hosts: all
  tasks:
    - package:
        name: cron
        state: present
    - service:
        name: cron
        state: started
        enabled: yes
    - copy:
        src: ./scripts/target_host_health_check.sh
        dest: /target_host_health_check.sh
    - cron: 
        name: Checking the health staus
        job: sh ./target_host_health_check.sh
        minute: 05
        hour: 06
        day: 1-31
        month: 1-12
        weekday: 0-6
    - command: crontab -l
      register: result_cronjobs
    - debug:
        var: result_cronjobs.stdout_lines
    - script: ./scripts/configure_cronjob_logs_file.sh 
      delegate_to: localhost
    - copy: 
        content: '{{ result_cronjobs.stdout }}'
        dest: './cronjob_logs/{{ inventory_hostname }}_cronjob_log.txt'
      delegate_to: localhost
        #run_once: true
    - shell: 'cat ./cronjob_logs/{{ inventory_hostname }}_cronjob_log.txt'
      delegate_to: localhost
    - shell: 'rm -rvf ./cronjob_logs/* ./cronjob_logs'
      delegate_to: localhost
      run_once: true
      
