- name: To clear the tmp created within target servers
  hosts: web_db
  tasks:
    - package:
        name: cron
        state: present
    - service:
        name: cron
        state: started
        enabled: yes
    - cron: 
        name: Clear tmp files cronjob
        job: rm -rvf /tmp/*
        minute: 30
        hour: 00
        day: '*'
        month: '*'
        weekday: '*'
