- name: To update the package manager  within target servers
  hosts: web_db
  tasks:
    - package:
        name: cron
        state: present
    - service:
        name: cron
        state: started
        enabled: yes
    - cron: 
        name: Update package manager cronjob
        job: 'apt-get update -y'
        minute: o0
        hour: 12
        day: '*/7'
        month: '*'
        weekday: '1-5'
