- name: 'Install & Run Nginx Webserver'
  hosts: localhost
  tasks:
    - name: 'Install Nginx'
      apt:
        name: nginx
        state: present
    - name: 'Start Service'
      service:
        name: nginx
        state: started
    - name: 'Access the Default nginx Webpage'
      shell: 'curl $(hostname -i)'
