---
- name: 'Demo Jinja2 Template'
  hosts: localhost
  vars:
    fruits:
      - orange
      - mango
      - banana
    vegetables:
      - name: 'Okra'
        price: '2$'
      - name: 'cluster beans'
        price: '1$'
      - name: 'Brassica oleracea'
        price: '0.7$'
  tasks:
    - name: 'create demofiles directory'
      command: 'mkdir -p ./demofiles'
    - name: 'Copy dummyText.txt file from local to target host'
      template: 
        src: './templates/dummyText.txt.j2'
        dest: './demofiles/dummyText.txt'
    - name: 'access ./demofiles/dummyText.txt file'
      command: 'cat ./demofiles/dummyText.txt'
