- name: Run linux cat cmd
  hosts: web
  tasks:
    - shell: echo "Hi this is an example of ansible register directive check!!" > ansible_register_sample.txt
      register: result
      
    - name: Print the result var
      debug:
        var: result
    
    - name: Print the result.rc
      debug:
        var: result.rc

    - name: Print the result.stdout
      debug:
        var: result.stdout

    - name: Print the result.stdout_lines
      debug:
        var: result.stdout_lines

    - name: Print the result.stderr
      debug:
        var: result.stderr
