- name: Demo Java Login Webpage App over tomcat server
  hosts: localhost
  become: true
  tasks:
    - name: 'Install java package'
      package:
        name: 'java-25-openjdk.x86_64'
        state: present

    - name: 'Create tomcat group'
      group:
        name: tomcat

    - name: 'Create tomcat user'
      user:
        name: tomcat
        state: present
        uid: 1011
        group: tomcat
        home: /usr/share/tomcat
        createhome: false

    - name: 'Download Tomcat'
      get_url:
        url: 'https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.117/bin/apache-tomcat-9.0.117.tar.gz'
        dest: '/opt/'

    - name: 'Extract apache-tomcat-9.0.117.tar.gz file to /opt/ directory'
      unarchive:
        src: '/opt/apache-tomcat-9.0.117.tar.gz'
        dest: '/opt/'
        remote_src: true

    - name: Create symlink for Tomcat
      file:
        src: /opt/apache-tomcat-9.0.117
        path: /usr/share/tomcat
        state: link

    - name: 'Change ownership of /usr/share/tomcat/apache-tomcat-9.0.117 directory'
      file:
        path: '/usr/share/tomcat/'
        owner: tomcat
        group: tomcat
        state: directory

    - name: 'Download the Java Code'
      git:
        repo: https://github.com/ranjit4github/LoginWebApp.git
        dest: /mnt
        version: master
        force: yes

    - name: 'Install maven package'
      package:
        name: 'maven'
        state: present

    - name: 'Create .war file from artifacts'
      command: mvn install -X
      args:
        chdir: /mnt


    - name: 'Copy .war to tomcat/webapps directory'
      copy:
        src: /mnt/target/LoginWebApp.war
        dest: /usr/share/tomcat/webapps/LoginWebApp.war

    - name: 'Start tomcat server'
      shell: '/usr/share/tomcat/bin/catalina.sh start'

