- name: Demo nginx server
  hosts: web
  tasks:
    - name: Install nginx server
      apt:
        name: nginx
        state: present
    - name: nginx service start
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Get the IP Address of current server
      command: hostname -i
      register: result
    - name: Show IP Address for current server
      debug:
        var: result.stdout
    - name: Access default nginx webpage
      command: 'curl {{ result.stdout }}'
    - name: Added custom webpage 
      script: configureindexfile.sh
    - name: nginx service restart
      service:
        name: nginx
        state: restarted
    - name: Access custom webpage nginx webpage
      command: 'curl {{ result.stdout }}/custom_webpage'
