- name: 'Demo become directive'
  hosts: web
  tasks:
    - name: 'list out the users'
      command: getent passwd
    - name: 'becoming web_user user & executing whoami command'
      become: yes
      become_user: web_user
      become_method: sudo
      command: whoami
    - name: 'Install nginx service'
      become: yes
      become_user: web_user
      become_method: sudo
      apt:
        name: nginx
        state: latest
    - name: 'Start nginx service'
      become: yes
      become_user: web_user
      become_method: sudo
      service:
        name: nginx
        state: started
    - name: 'becoming admin & executing whoami command'
      become: yes
      become_user: admin
      become_method: sudo
      command: whoami
    - name: 'access nginx service'
      shell: curl $(hostname -i)
