- name: Demo Java Login Webpage App over tomcat server
  hosts: localhost
  become: true
  tasks:
    - name: 'Install java package'
      package:
        name: 'java-11-amazon-corretto.x86_64'
        state: present
      tags: 'Install-java'

    - name: 'Create tomcat group'
      group:
        name: tomcat
      tags: "Install-tomcat"

    - name: 'Create tomcat user'
      user:
        name: tomcat
        state: present
        uid: 1011
        group: tomcat
        home: /usr/share/tomcat
        createhome: false
      tags: "Install-tomcat"

    - name: 'Download Tomcat'
      get_url:
        url: 'https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.117/bin/apache-tomcat-9.0.117.tar.gz'
        dest: '/opt/'
      tags: "Install-tomcat"

    - name: 'Extract apache-tomcat-9.0.117.tar.gz file to /opt/ directory'
      unarchive:
        src: '/opt/apache-tomcat-9.0.117.tar.gz'
        dest: '/opt/'
        remote_src: true
      tags: "Install-tomcat"

    - name: Create symlink for Tomcat
      file:
        src: /opt/apache-tomcat-9.0.117
        path: /usr/share/tomcat
        state: link
      tags: "Install-tomcat"

    - name: 'Change ownership of /usr/share/tomcat/apache-tomcat-9.0.117 directory'
      file:
        path: '/usr/share/tomcat/'
        owner: tomcat
        group: tomcat
        state: directory
        mode: '0755'
      tags: "Install-tomcat"

    - name: 'Download Jenkins Server .war file'
      get_url:
        url: 'https://get.jenkins.io/war-stable/2.555.1/jenkins.war'
        dest: '/usr/share/tomcat/webapps/jenkins.war'
        owner: tomcat
        group: tomcat
        mode: '0644'
      tags: "Install-jenkins"

    - name: 'Start tomcat server'
      shell: '/usr/share/tomcat/bin/startup.sh'
