- name: Print ansible_facts for db1 host
  hosts: web
  gather_facts: yes
  tasks:
    - name: Print ansible_host for db1 host
      debug:
        msg: 'db1 host ip adddress is: {{ hostvars["db1"].ansible_host }}'
    - name: Print ansible_facts for web group 
      debug:
        var: ansible_facts
    - name: Print web host architecture & os_family
      debug:
        msg: 'Architecture is: {{ ansible_facts.architecture }} OS Family is: {{ ansible_facts.os_family }}'
    - name: Print web host IP Address
      debug:
        var: ansible_facts.eth0.ipv4.address
    - name: Print web host MAC Address
      debug:
        var: ansible_facts.eth0.macaddress
    - name: Print FQDN for web host
      debug:
        msg: 'Fully Qualified Domain Name: {{ ansible_facts.fqdn }}'
