- name: Print ansible_facts for db1 host
  hosts: web
  tasks:
    - name: Print ansible_host for db1 host
      debug:
        msg: '{{ hostvars["db1"].ansible_host }}'
    - name: Print ansible_facts for db1 host
      debug:
        var: '{{ hostvars["db1"].ansible_facts }}'
